### ISSUE TITLE
OS X: TypeError: 'module' object is not callable

### ISSUE THREAD

**Issue by hugovk** [araile/see#12]
Following the readme:

```bash
$ pip install --upgrade see
Collecting see
Installing collected packages: see
Successfully installed see-1.2.0

$ python
```
```python
Python 2.7.10 (default, Sep 23 2015, 04:34:21) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.72)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from see import see
>>> foo = 'bar'
>>> see()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'module' object is not callable
```

**Comment by hugovk** [comment]
I get the same for all the pip installable versions, back to 0.4.0.

**Comment by hugovk** [comment]
Back to latest 1.2.0, this works:
```python
Python 2.7.10 (default, Sep 23 2015, 04:34:21) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.72)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from see import see
>>> dir(see)
['PY_300', 'PY_301', 'PY_350', 'SYMBOLS', 'SeeError', '_LOCALS', '_SeeDefault', '_SeeOutput', '__all__', '__author__', '__builtins__', '__contributors__', '__copyright__', '__doc__', '__file__', '__license__', '__name__', '__package__', '__version__', 'fcntl', 'fn_filter', 'fnmatch', 'inspect', 'line_width', 're', 'regex_filter', 'see', 'struct', 'sys', 'term_width', 'termios', 'textwrap']
>>> foo = 'bar'
>>> see()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'module' object is not callable
>>> see.see()
    foo    see
>>> 
```

**Comment by araile** [comment]
It might be importing a leftover .pyc file.

Are you running Python from the see directory? Does it work if you `cd /tmp` and try again?

**Comment by hugovk** [comment]
Thanks, got it working!

Well, as it happens there was a leftover see directory in /tmp, but I get the same thing after getting rid of it. So I did:
```bash
$ pip uninstall see
Uninstalling see-1.2.0:
  /usr/local/lib/python2.7/site-packages/see-1.2.0.dist-info/DESCRIPTION.rst
  /usr/local/lib/python2.7/site-packages/see-1.2.0.dist-info/INSTALLER
  /usr/local/lib/python2.7/site-packages/see-1.2.0.dist-info/METADATA
  /usr/local/lib/python2.7/site-packages/see-1.2.0.dist-info/RECORD
  /usr/local/lib/python2.7/site-packages/see-1.2.0.dist-info/WHEEL
  /usr/local/lib/python2.7/site-packages/see-1.2.0.dist-info/metadata.json
  /usr/local/lib/python2.7/site-packages/see-1.2.0.dist-info/top_level.txt
  /usr/local/lib/python2.7/site-packages/see.py
  /usr/local/lib/python2.7/site-packages/see.pyc
Proceed (y/n)? y
  Successfully uninstalled see-1.2.0
$ pip uninstall see
Cannot uninstall requirement see, not installed
$ cd /usr/local/lib/python2.7/site-packages/
$ ls see/
__init__.py	__init__.pyc	see.py		see.pyc
```

So there was some old installation stuff there, despite what pip said. So I got rid of that dir and reinstalled and it works.

Thanks for pointing me in the right direction!
